# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: feaf31e395bfd62fef93928fe83eea6e7041bd58c536dcdb87bf19fec3c3479365c02785bd2c565b09efd96dc90eb8a20dd1b1d7670ac06aad5a043496fdbfb0

test:
  secret_key_base: 59068321e01a6e196884e1fb0af120c929c7bb60dc12621da35f5fb1600e22fc141a1211094b1157fb5fa49f8ccf50d5b4e11cccb3b6213619416acc7ae056b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
